/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smsystem;

import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class reportcard extends javax.swing.JFrame {

    /**
     * Creates new form reportcard
     */
    public reportcard() {
        initComponents();
//        comboBox3();
//        comboBox1();
//        comboBox2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
//    public void comboBox2(){
//        
//        try{
//            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
//            java.sql.Connection connection;
//            connection = DriverManager
//                    .getConnection(
//            "jdbc:sqlserver://localhost:1433;databaseName=SavetheFuture;selectMethod=cursor", "sa", "123456");
//             String sql = "SELECT * From Semester";
//            PreparedStatement pstt= connection.prepareStatement(sql);
//            ResultSet rs = pstt.executeQuery();
//            while(rs.next()){
//                jComboBox2.addItem(rs.getString("Department"));
//            }
//        }catch(Exception e){
//            
//        }
//    }
    
//    public void comboBox1(){
//        
//        try{
//            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
//            java.sql.Connection connection;
//            connection = DriverManager
//                    .getConnection(
//            "jdbc:sqlserver://localhost:1433;databaseName=SavetheFuture;selectMethod=cursor", "sa", "123456");
//             String sql = "SELECT * From Semester";
//            PreparedStatement pstt= connection.prepareStatement(sql);
//            ResultSet rs = pstt.executeQuery();
//            while(rs.next()){
//                jComboBox1.addItem(rs.getText("Semester_no"));
//            }
//        }catch(Exception e){
//            
//        }
//    }
    
//    public void comboBox3(){
//        
//        try{
//            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
//            java.sql.Connection connection;
//            connection = DriverManager
//                    .getConnection(
//            "jdbc:sqlserver://localhost:1433;databaseName=SavetheFuture;selectMethod=cursor", "sa", "123456");
//             String sql = "SELECT * From Semester";
//            PreparedStatement pst= connection.prepareStatement(sql);
//            ResultSet rs = pst.executeQuery();
//            while(rs.next()){
//                jComboBox3.addItem(rs.getString("Course_no"));
//            }
//        }catch(Exception e){
//            
//        }
//    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        text = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        q1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        q2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        q3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        q4 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        attend = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        finalm = new javax.swing.JTextField();
        course = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        sem1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        sem2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setViewportView(text);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 0, 490, 700));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("RESULT");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, 50));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ID :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 30, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Semester :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 230, 30));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("..................................................................................................................................................................................");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 710, -1));

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 660, -1, -1));

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("QUIZ 1 :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 60, 20));

        q1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1ActionPerformed(evt);
            }
        });
        getContentPane().add(q1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 190, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("QUIZ 2 :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 470, 70, 20));
        getContentPane().add(q2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, 190, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("QUIZ 3 :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 520, 80, 30));
        getContentPane().add(q3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 520, 190, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("QUIZ 4 :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, 70, 30));
        getContentPane().add(q4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 420, 180, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ATTENDANCE :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 470, 110, 30));
        getContentPane().add(attend, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 470, 180, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Final Marks :");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 520, -1, -1));
        getContentPane().add(finalm, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 510, 180, 30));
        getContentPane().add(course, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 220, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Course No :");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));
        getContentPane().add(sem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 220, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smsystem/frontbk1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1200, 700));
        getContentPane().add(sem2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 220, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new teacher_dashboard().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
        try{
              Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            java.sql.Connection connection;
            connection = DriverManager
                    .getConnection(
            "jdbc:sqlserver://localhost:1433;databaseName=SavetheFuture;selectMethod=cursor", "sa", "123456");
            
            String sql = "insert into Resultinfo(StudentId,Course,Semester) values(?,?,?)";
             String sql2 = "insert into marks(ID,Quiz01,Quiz02,Quiz03,Quiz04,Attendance,Final) values(?,?,?,?,?,?,?)";
           //  String sql3 = "select * from resultinfo.StudentId,resultinfo.Course,resultinfo.Semsester,marks.quiz01,marks.quiz02,marks.quiz03,marks.quiz04 values(?,?,?,?,?,?)";
            String sid=id.getText();
            String semester=course.getText();
            
            String courseNo=course.getText();
            
            //String sem=jComboBox1.getText();
            //String department=jComboBox2.setText(dept);
            String quiz1=q1.getText();
            String quiz2=q2.getText();
            String quiz3=q3.getText();
            String quiz4=q4.getText();
            String attendance=attend.getText();
            String finalmarks=finalm.getText();
          
            
            
            
            
            
             PreparedStatement ptst= connection.prepareStatement(sql);
            ptst.setString(1, id.getText());
            
            ptst.setString(2, course.getText());
            
            ptst.setString(3, course.getText());
            
            ptst.executeUpdate();
            
            PreparedStatement ptst2= connection.prepareStatement(sql2);
             ptst2.setString(1, id.getText());
            ptst2.setString(2, q1.getText());
            ptst2.setString(3, q2.getText());
            ptst2.setString(4, q3.getText());
            ptst2.setString(5, q4.getText());
            ptst2.setString(6, attend.getText());
            ptst2.setString(7, finalm.getText());
            ptst2.executeUpdate();
           
            
           
           // ptst.setString(5, r);
            
            
           
            JOptionPane.showMessageDialog(null, "Data has been saved");
            
            text.setText("REPORT CARD\n\n Student ID: "+sid+"\nSemester: "+semester+"\n"
                    + "Course: "+course+"\n\n Quiz 1:"+quiz1+"\n\n Quiz 2:"+quiz2+"\n\n Quiz 3:"+quiz3+
                    "\n\n Quiz 4:"+quiz4+"\n\n Attendance:"+attendance+"\n\n Final :"+finalmarks
                    );
            
          
            
            
            connection.close();
            
            
            
            
        }
        catch(Exception e){
             JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void q1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reportcard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reportcard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reportcard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reportcard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reportcard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField attend;
    private javax.swing.JTextField course;
    private javax.swing.JTextField finalm;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField q1;
    private javax.swing.JTextField q2;
    private javax.swing.JTextField q3;
    private javax.swing.JTextField q4;
    private javax.swing.JTextField sem1;
    private javax.swing.JTextField sem2;
    private javax.swing.JTextPane text;
    // End of variables declaration//GEN-END:variables

    
}
