/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class teacherRegForm extends javax.swing.JFrame {

    /**
     * Creates new form teacherRegForm
     */
    public teacherRegForm() {
        initComponents();
         setSize(1200,700);
        setTitle("Student Management System");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabelRegister = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_tEmail = new javax.swing.JTextField();
        jPasswordField_REPASS = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField_tID = new javax.swing.JTextField();
        jTextField_tLastName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField_tPhone = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_tdes = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField_tFirstName = new javax.swing.JTextField();
        jPasswordField_PASS = new javax.swing.JPasswordField();
        Jbutton_Register_ = new javax.swing.JButton();
        jButton_CANCEL = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("REGISTER");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 220, 60));

        jLabelRegister.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelRegister.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegister.setText("Click Here to Login");
        jLabelRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRegisterMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 540, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(236, 240, 241));
        jLabel11.setText("Email : ");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(236, 240, 241));
        jLabel6.setText("ReType Pass : ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, -1, -1));

        jTextField_tEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_tEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_tEmailActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_tEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, 250, 30));

        jPasswordField_REPASS.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jPasswordField_REPASS, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 430, 260, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(236, 240, 241));
        jLabel12.setText("Teacher ID : ");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(236, 240, 241));
        jLabel7.setText("Last Name : ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, -1));

        jTextField_tID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_tID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_tIDActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_tID, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, 250, 30));

        jTextField_tLastName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_tLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_tLastNameActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_tLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, 250, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(236, 240, 241));
        jLabel9.setText("Phone NO : ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, -1, -1));

        jTextField_tPhone.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_tPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_tPhoneActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_tPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 240, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(236, 240, 241));
        jLabel10.setText("Designation :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(236, 240, 241));
        jLabel4.setText("First Name : ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, -1, -1));

        jTextField_tdes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_tdes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_tdesActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_tdes, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 250, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(236, 240, 241));
        jLabel5.setText("Password : ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, -1, -1));

        jTextField_tFirstName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_tFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_tFirstNameActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_tFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 250, 30));

        jPasswordField_PASS.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPasswordField_PASS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField_PASSActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField_PASS, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 380, 260, 30));

        Jbutton_Register_.setBackground(new java.awt.Color(34, 167, 240));
        Jbutton_Register_.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Jbutton_Register_.setText("Register");
        Jbutton_Register_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Jbutton_Register_MouseClicked(evt);
            }
        });
        Jbutton_Register_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbutton_Register_ActionPerformed(evt);
            }
        });
        getContentPane().add(Jbutton_Register_, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 480, -1, -1));

        jButton_CANCEL.setBackground(new java.awt.Color(192, 57, 43));
        jButton_CANCEL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_CANCEL.setText("Cancel");
        jButton_CANCEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CANCELActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_CANCEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 480, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smsystem/frontbk1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegisterMouseClicked
        // TODO add your handling code here:
        teacherlogin lgf = new teacherlogin();
        lgf.setVisible(true);
        lgf.pack();
        lgf.setLocationRelativeTo(null);
        lgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabelRegisterMouseClicked

    private void jTextField_tEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_tEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_tEmailActionPerformed

    private void jTextField_tIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_tIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_tIDActionPerformed

    private void jTextField_tLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_tLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_tLastNameActionPerformed

    private void jTextField_tPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_tPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_tPhoneActionPerformed

    private void jTextField_tdesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_tdesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_tdesActionPerformed

    private void jTextField_tFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_tFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_tFirstNameActionPerformed

    private void jPasswordField_PASSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField_PASSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField_PASSActionPerformed

    private void Jbutton_Register_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jbutton_Register_MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Jbutton_Register_MouseClicked

    private void Jbutton_Register_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbutton_Register_ActionPerformed
        // TODO add your handling code here:

        String tfname = jTextField_tFirstName.getText();
        String tlname = jTextField_tLastName.getText();
        String tdes = jTextField_tdes.getText();
        String tphn = jTextField_tPhone.getText();
        String tID = jTextField_tID.getText();
        String temail = jTextField_tEmail.getText();

        String pass = String.valueOf(jPasswordField_PASS.getPassword());

        String re_pass = String.valueOf(jPasswordField_REPASS.getPassword());

        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connection = DriverManager
            .getConnection(
                "jdbc:sqlserver://localhost:1433;databaseName=SavetheFuture;selectMethod=cursor", "sa", "123456");
            
            String query = "INSERT INTO Teacher(TeacherId, Teacher_FirstName, Teacher_LastName , Teacher_Designation,Teacher_Email,password,Teacher_PhoneNo )VALUES (?,?,?,?,?,?,?)";
            PreparedStatement pst=connection.prepareStatement(query);

            pst.setString(1, tID);
            pst.setString(2, tfname);
            pst.setString(3, tlname);
            pst.setString(4, tdes);
            pst.setString(5, temail);
            pst.setString(6, pass);
            
            pst.setString(7, tphn);

            if(tID.equals(""))
            {
                JOptionPane.showMessageDialog(null, "Add Teacher ID");
            }

            else if(pass.equals(""))
            {
                JOptionPane.showMessageDialog(null, "Add A Password");
            }
            else if(!pass.equals(re_pass))
            {
                JOptionPane.showMessageDialog(null, "Retype The Password Again");
            }
            else if(checkTeacherID(tID))
            {
                JOptionPane.showMessageDialog(null, "This Studemt Already Exists");
            }
            if(pst.executeUpdate() > 0)
            {
                JOptionPane.showMessageDialog(null, "New Teacher Add");
            }

        } catch (SQLException ex) {
            Logger.getLogger(teacherRegForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(teacherRegForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Jbutton_Register_ActionPerformed

    private void jButton_CANCELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CANCELActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton_CANCELActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(teacherRegForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(teacherRegForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(teacherRegForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(teacherRegForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new teacherRegForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jbutton_Register_;
    private javax.swing.JButton jButton_CANCEL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelRegister;
    private javax.swing.JPasswordField jPasswordField_PASS;
    private javax.swing.JPasswordField jPasswordField_REPASS;
    private javax.swing.JTextField jTextField_tEmail;
    private javax.swing.JTextField jTextField_tFirstName;
    private javax.swing.JTextField jTextField_tID;
    private javax.swing.JTextField jTextField_tLastName;
    private javax.swing.JTextField jTextField_tPhone;
    private javax.swing.JTextField jTextField_tdes;
    // End of variables declaration//GEN-END:variables

    public boolean checkTeacherID(String tID) throws ClassNotFoundException
    {
        PreparedStatement ps;
        ResultSet rs;
        boolean checkUser = false;
        String query = "SELECT * FROM Teacher WHERE TeacherId=?";
        
        try {
              Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connection = DriverManager
            .getConnection(
              "jdbc:sqlserver://localhost:1433;databaseName=SavetheFuture;selectMethod=cursor", "sa", "123456");
           
             ps=connection.prepareStatement(query);
            ps.setString(1, tID);
            
            rs = ps.executeQuery();
            
            if(rs.next())
            {
                checkUser = true;
            }
        } catch (SQLException ex) {
            Logger.getLogger(teacherRegForm.class.getName()).log(Level.SEVERE, null, ex);
        }
         return checkUser;
    }

    
}
